from pathlib import Path
p=Path('project_docs/RESEARCH_FULL_RESTART_2026-09-01_BASELINE.md')
t=p.read_text(encoding='utf-8')
old='| C33 | CSS/WAAPI animations/transitions | `NOT-TRIAGED / UNKNOWN` |'
new='| C33 | CSS/WAAPI animations/transitions | `L4-REVALIDATED / FINDING + POSITIVE/CSS/WAAPI/TRANSITION/PAUSED/FROZEN/FRAME/CAUSAL CONTROLS (P0-070, P1-187; P0-075 supporting)` |'
if old not in t: raise SystemExit('C33 row mismatch')
t=t.replace(old,new,1)
checkpoint='''\n\n## Fresh continuation checkpoint — focused C33 CSS/WAAPI animations/transitions\n\n`RESEARCH_FULL_RESTART_C33_CSS_WAAPI_TEMPORAL_2026-09-02.md` records the accepted fresh C33 exact-source physical tranche on canonical source `72a2efc2ca298b623d5650d44f8430163f0aa876`, exact `content.js` blob `f3ee7b51fe9ee94fdfe36e8a7c99f14a548fdc4e`, exact `pdf-print-guard.js` blob `423c79143df37a80fbabf8cbbf7570a4a2ca4e2a`, Google Chrome `151.0.7922.173`, workflow run `33650829793`, job `100317097988`, exact workflow head `eea937d13bc5eb66a930a530c624d5f44e649845`, conclusion SUCCESS and raw result SHA-256 `29d5a8cbda55f1edcc2a7e91150a94a8029aa5a429050af73026a2f22c5b2388`.\n\nFresh top-document evidence proves CSS animation, WAAPI animation and CSS transition advance materially after admission and the physical PDF reflects the later render-cut phase rather than the admitted phase. Already-paused and sampled/frozen controls remain stable and physically reproduce the sampled state, proving current Chrome can serialize a stable non-zero temporal presentation when the final representation is made time-invariant. The current render-cut script-execution guard is therefore not a temporal timeline snapshot, and actual save metadata contains no temporal phase receipt.\n\nSame-origin BODY flattening independently revalidates **P1-187 ACTIVE**: the source has one running WAAPI animation and non-zero sampled transform, while the final proxy has zero animations, `transform:none`, and zero temporal displacement. Applying only the admitted sampled transform to the final proxy restores the temporal displacement in physical PDF. The top-document drift maps primarily to **P0-070 ACTIVE**; **P0-075 ACTIVE** remains supporting isolation architecture. No new P-code or Registry wording/status change is warranted. C33 therefore advances to `L4-REVALIDATED / FINDING + POSITIVE/CSS/WAAPI/TRANSITION/PAUSED/FROZEN/FRAME/CAUSAL CONTROLS (P0-070, P1-187; P0-075 supporting)`. C34 — Animated image/GIF frame — is the next sequential coordinate.\n'''
anchor='\n## Delivery rule\n'
if anchor not in t: raise SystemExit('delivery anchor missing')
t=t.replace(anchor,checkpoint+anchor,1)
p.write_text(t,encoding='utf-8')
