from pathlib import Path
p=Path('project_docs/RESEARCH_FULL_RESTART_2026-09-01_BASELINE.md')
text=p.read_text(encoding='utf-8')
old='| C36 | Same locator/URL, different resource bytes/generation | `NOT-TRIAGED / UNKNOWN` |'
new='| C36 | Same locator/URL, different resource bytes/generation | `L4-REVALIDATED / FINDING + POSITIVE/STABLE-IMG/SAME-URL/SRCSET/BACKGROUND/CACHE-EVICTION/FROZEN/CAUSAL CONTROLS (P0-070, P0-004; P1-003 supporting)` |'
if old not in text: raise SystemExit('C36 baseline row mismatch')
text=text.replace(old,new,1)
checkpoint='''\n\n## Fresh continuation checkpoint — focused C36 Same locator/URL, different resource bytes/generation\n\n`RESEARCH_FULL_RESTART_C36_RESOURCE_BYTE_GENERATION_2026-09-02.md` records the accepted fresh C36 exact-source tranche on canonical source `b6b008dceec0b787ca1283e6c822fcd5f3abddcb`, exact `content.js` blob `f3ee7b51fe9ee94fdfe36e8a7c99f14a548fdc4e`, Chrome `152.0.7977.64`, workflow run `33658450070`, job `100342779251`, exact workflow head `c7ddbbd54b8c83d69b67f312a21a324a2bac211e`, conclusion SUCCESS, main result SHA-256 `0e364a58fc95ae41aa74f92c98d26c9272ce5fba029f7b2441f2b9c38932265e` and cache-eviction result SHA-256 `1d46d8ea5e36f042f1463d5f59944165f9123684dded7ee21272a6e86dd52257`.\n\nFresh controls prove that ordinary already-decoded IMG/currentSrc reuse can preserve admitted bytes despite a newer server generation, and a frozen admission-byte data URL remains stable. The decisive case clears browser cache after admitted red pixels, changes the origin to green bytes at the exact same URL, then lets current WebClip promote same-URL `data-srcset`. Browser candidate resolution fetches green; DOM locator, src/currentSrc URL and natural dimensions remain textually unchanged, but physical PDF changes from admitted red to green. A background control separately fetches green during readiness probing while final PDF remains red despite a clean loaded report, proving URL task settlement is not final renderer byte-generation identity.\n\nDuplicate/root-cause reconciliation maps C36 to existing **P0-070 / P0-004 ACTIVE**, with **P1-003 ACTIVE** supporting readiness/provenance. C40/P0-023/P0-079 are not exercised because no PDF retry/cache reuse occurs. No new P-code or Registry wording/status change is warranted. C36 advances to `L4-REVALIDATED / FINDING + POSITIVE/STABLE-IMG/SAME-URL/SRCSET/BACKGROUND/CACHE-EVICTION/FROZEN/CAUSAL CONTROLS (P0-070, P0-004; P1-003 supporting)`. C37 — Failure / retry / rollback / convergence — is the next sequential coordinate.\n'''
anchor='\n## Delivery rule\n'
if anchor not in text: raise SystemExit('Delivery rule anchor missing')
text=text.replace(anchor,checkpoint+anchor,1)
p.write_text(text,encoding='utf-8')
