#!/usr/bin/env python3
"""Physical P1-231 PSL regeneration proof for one exact Git commit.

This helper is intentionally release-neutral. It reads the generator, input and
committed output from exact Git blobs, regenerates in an isolated temporary
workspace, and fails unless the generated bytes exactly match the committed
output under CPython 3.12.10.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import platform
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
GENERATOR = "project_tools/build_public_suffix_js.py"
SOURCE = "public_suffix_list.dat"
OUTPUT = "public-suffix.js"
EXPECTED_PYTHON = (3, 12, 10)


def run_git(*args: str, binary: bool = False):
    result = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout if binary else result.stdout.decode("utf-8").strip()


def git_entry(commit: str, rel: str) -> dict[str, str]:
    raw = run_git("ls-tree", commit, "--", rel)
    if not raw or "\t" not in raw:
        raise RuntimeError(f"missing Git entry: {rel}")
    left, path = raw.split("\t", 1)
    mode, kind, oid = left.split()
    if path != rel or mode != "100644" or kind != "blob":
        raise RuntimeError(f"unexpected Git entry for {rel}: {raw}")
    return {"path": path, "mode": mode, "type": kind, "oid": oid}


def exact_blob(commit: str, rel: str) -> bytes:
    entry = git_entry(commit, rel)
    return run_git("cat-file", "blob", entry["oid"], binary=True)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--expected-sha", required=True)
    args = parser.parse_args()

    head = run_git("rev-parse", "HEAD")
    if head != args.expected_sha:
        raise RuntimeError(f"exact checkout mismatch: expected {args.expected_sha}, got {head}")
    if run_git("cat-file", "-t", head) != "commit":
        raise RuntimeError("HEAD is not a commit")

    if platform.python_implementation() != "CPython":
        raise RuntimeError(f"unsupported Python implementation: {platform.python_implementation()}")
    if sys.version_info[:3] != EXPECTED_PYTHON:
        raise RuntimeError(
            f"runtime profile mismatch: expected CPython 3.12.10, got {platform.python_version()}"
        )

    entries = {rel: git_entry(head, rel) for rel in (GENERATOR, SOURCE, OUTPUT)}
    generator = exact_blob(head, GENERATOR)
    source = exact_blob(head, SOURCE)
    candidate = exact_blob(head, OUTPUT)

    with tempfile.TemporaryDirectory(prefix="webclip-p1-231-psl-") as tmp:
        root = pathlib.Path(tmp)
        (root / "project_tools").mkdir()
        (root / GENERATOR).write_bytes(generator)
        (root / SOURCE).write_bytes(source)

        proc = subprocess.run(
            [sys.executable, GENERATOR],
            cwd=root,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        generated_path = root / OUTPUT
        if not generated_path.is_file():
            raise RuntimeError("generator did not create public-suffix.js")
        generated = generated_path.read_bytes()

        top = sorted(p.name for p in root.iterdir())
        if top != ["project_tools", "public-suffix.js", "public_suffix_list.dat"]:
            raise RuntimeError(f"unexpected isolated workspace contents: {top}")

    if generated != candidate:
        raise RuntimeError(
            "generated bytes differ from committed output: "
            f"generated_sha256={sha256(generated)} candidate_sha256={sha256(candidate)}"
        )

    result = {
        "schema": "webclip-p1-231-psl-portability-observation/v1",
        "candidateSha": head,
        "platform": platform.system(),
        "platformRelease": platform.release(),
        "pythonImplementation": platform.python_implementation(),
        "pythonVersion": platform.python_version(),
        "osLineSeparatorHex": os.linesep.encode("utf-8").hex(),
        "generator": {
            "path": GENERATOR,
            "gitOid": entries[GENERATOR]["oid"],
            "sha256": sha256(generator),
        },
        "input": {
            "path": SOURCE,
            "gitOid": entries[SOURCE]["oid"],
            "sha256": sha256(source),
        },
        "output": {
            "path": OUTPUT,
            "gitOid": entries[OUTPUT]["oid"],
            "sha256": sha256(candidate),
            "generatedSha256": sha256(generated),
            "byteLength": len(candidate),
            "exactMatch": True,
            "crlfCount": candidate.count(b"\r\n"),
        },
        "generatorStdoutSha256": sha256(proc.stdout),
        "generatorStderrSha256": sha256(proc.stderr),
    }
    print("P1-231 PSL portability evidence: PASS; " + json.dumps(result, sort_keys=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
