#!/usr/bin/env node
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import puppeteer from 'puppeteer';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const MANIFEST=JSON.parse(fs.readFileSync(path.join(ROOT,'manifest.json'),'utf8'));
const POPUP=fs.readFileSync(path.join(ROOT,'popup.js'),'utf8');
const WORKER=fs.readFileSync(path.join(ROOT,'service-worker.js'),'utf8');
const FRAME=fs.readFileSync(path.join(ROOT,'frame-agent.js'),'utf8');
const TITLE='C46 real unpacked debugger fixture';
function source(){const p=new Set(MANIFEST.permissions||[]),h=new Set(MANIFEST.optional_host_permissions||[]);const g=POPUP.slice(POPUP.indexOf("grantFrameAccessButton?.addEventListener('click'"),POPUP.indexOf("readLaterButton.addEventListener"));const r={debugger:p.has('debugger'),http:h.has('http://*/*'),https:h.has('https://*/*'),incognitoKey:Object.hasOwn(MANIFEST,'incognito'),backupBeforeTab:POPUP.indexOf('loadBackupStatus();')<POPUP.indexOf('async function getActiveSourceTab'),requestAfterDiscovery:g.indexOf('await collectCrossOriginFrameOrigins')>=0&&g.indexOf('await collectCrossOriginFrameOrigins')<g.indexOf('chrome.permissions.request'),popupTimeout:/POPUP_EXTENSION_API_TIMEOUT_MS\s*=\s*10_000/.test(POPUP),incognitoGuard:WORKER.includes('sender?.tab?.incognito'),onRemoved:WORKER.includes('chrome.permissions.onRemoved'),permRecheck:WORKER.includes('frameAgentHasGrantedHostPermission'),memoryRegistry:WORKER.includes('frameAgentsByTab = new Map()'),reregister:FRAME.includes('__WEBCLIP_FRAME_AGENT_LOADED__')&&FRAME.includes('WEBCLIP_FRAME_AGENT_REGISTER'),attach:WORKER.includes('async function attachDebuggerBounded'),detach:WORKER.includes('async function detachDebuggerBounded'),print:WORKER.includes("chrome.debugger.sendCommand(debuggee, 'Page.printToPDF'"),cleanup:['debuggerActiveTabs = new Set()','debuggerLateAttachCleanupByTab = new Map()','debuggerPendingDetachByTab = new Map()','debuggerPendingActualSettlements = new Set()','debuggerActiveTabs.delete(tabId)'].every(x=>WORKER.includes(x)),onDetach:WORKER.includes('debugger.onDetach')};for(const k of ['debugger','http','https','backupBeforeTab','requestAfterDiscovery','popupTimeout','incognitoGuard','permRecheck','memoryRegistry','reregister','attach','detach','print','cleanup'])assert.equal(r[k],true,k);assert.equal(r.incognitoKey,false);assert.equal(r.onRemoved,false);assert.equal(r.onDetach,false);return r;}
async function serve(){const server=http.createServer((req,res)=>{if((req.url||'').startsWith('/fixture')){const b=`<!doctype html><meta charset=utf-8><title>${TITLE}</title><h1>C46_REAL_UNPACKED_DEBUGGER_MARKER</h1>`;res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(b);return;}res.writeHead(404);res.end();});await new Promise((r,j)=>{server.once('error',j);server.listen(0,'127.0.0.1',r)});const {port}=server.address();return{server,url:`http://127.0.0.1:${port}/fixture`,pattern:`http://127.0.0.1:${port}/*`};}
function tempExt(f){const root=fs.mkdtempSync(path.join(os.tmpdir(),'c46-v3-')),ext=path.join(root,'extension');fs.cpSync(ROOT,ext,{recursive:true,filter(s){const rel=path.relative(ROOT,s);if(!rel)return true;return !['.git','node_modules'].includes(rel.split(path.sep)[0]);}});const side=`\n// C46 test-only storage trigger; temporary unpacked copy only.\nlet __c46Running=false;\nchrome.storage.onChanged.addListener((changes,area)=>{if(area!=='session'||!changes.__c46Trigger?.newValue||__c46Running)return;__c46Running=true;(async()=>{const out={ok:false,stage:'start'};let tab=null;try{out.incognitoAllowed=await chrome.extension.isAllowedIncognitoAccess();out.optionalOriginGrantedInitially=await chrome.permissions.contains({origins:[${JSON.stringify(f.pattern)}]});out.stage='tab-create';tab=await chrome.tabs.create({url:${JSON.stringify(f.url)},active:false});out.tabId=tab.id;out.stage='tab-load';for(let i=0;i<150;i++){const t=await chrome.tabs.get(tab.id);if(t.status==='complete')break;if(i===149)throw new Error('load-timeout');await new Promise(r=>setTimeout(r,100));}out.fixtureTitle=(await chrome.tabs.get(tab.id)).title||'';out.stage='before';out.debuggerAttachedBefore=Boolean((await chrome.debugger.getTargets()).find(x=>x.tabId===tab.id)?.attached);out.stage='generate';const blob=await generatePdfBlob(tab.id);const bytes=new Uint8Array(await blob.arrayBuffer());const dig=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));out.pdfBytes=bytes.length;out.pdfSha256=[...dig].map(x=>x.toString(16).padStart(2,'0')).join('');out.pdfHeaderHex=[...bytes.subarray(0,8)].map(x=>x.toString(16).padStart(2,'0')).join('');out.stage='after';out.debuggerAttachedAfter=Boolean((await chrome.debugger.getTargets()).find(x=>x.tabId===tab.id)?.attached);out.debuggerActiveSetAfter=debuggerActiveTabs.has(tab.id);out.debuggerLateAttachCleanupAfter=debuggerLateAttachCleanupByTab.has(tab.id);out.debuggerPendingDetachAfter=debuggerPendingDetachByTab.has(tab.id);out.debuggerPendingActualSettlementCountAfter=debuggerPendingActualSettlements.size;out.ok=true;out.stage='done';}catch(e){out.error=String(e?.stack||e?.message||e);}try{if(tab?.id)await chrome.tabs.remove(tab.id)}catch(_){}await chrome.storage.session.set({__c46Result:out});__c46Running=false;})().catch(async e=>{await chrome.storage.session.set({__c46Result:{ok:false,stage:'sidecar-top',error:String(e)}});__c46Running=false;});});\n`;fs.appendFileSync(path.join(ext,'service-worker.js'),side);fs.writeFileSync(path.join(ext,'c46-driver.html'),'<!doctype html><meta charset=utf-8><script src=c46-driver.js></script>');fs.writeFileSync(path.join(ext,'c46-driver.js'),`(async()=>{await chrome.storage.session.remove(['__c46Result']);await chrome.storage.session.set({__c46Trigger:Date.now()});for(let i=0;i<300;i++){const x=await chrome.storage.session.get('__c46Result');if(x.__c46Result){document.title='C46_DONE';return;}await new Promise(r=>setTimeout(r,100));}document.title='C46_TIMEOUT';})();`);return{root,ext};}
async function browser(f){const t=tempExt(f);let b;try{b=await puppeteer.launch({headless:false,pipe:true,enableExtensions:[t.ext],args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-first-run','--no-default-browser-check']});const sw=await b.waitForTarget(x=>x.type()==='service_worker'&&x.url().endsWith('/service-worker.js'),{timeout:30000});const id=new URL(sw.url()).host;const page=await b.newPage();await page.goto(`chrome-extension://${id}/c46-driver.html`);await page.waitForFunction(()=>document.title==='C46_DONE'||document.title==='C46_TIMEOUT',{timeout:35000});assert.equal(await page.title(),'C46_DONE');const result=await page.evaluate(async()=> (await chrome.storage.session.get('__c46Result')).__c46Result);assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.optionalOriginGrantedInitially,false);assert.equal(result.debuggerAttachedBefore,false);assert.equal(result.debuggerAttachedAfter,false);assert.equal(result.debuggerActiveSetAfter,false);assert.equal(result.debuggerLateAttachCleanupAfter,false);assert.equal(result.debuggerPendingDetachAfter,false);assert.equal(result.debuggerPendingActualSettlementCountAfter,0);assert.equal(result.fixtureTitle,TITLE);assert(Number(result.pdfBytes)>1000);assert.match(String(result.pdfSha256||''),/^[0-9a-f]{64}$/);assert(String(result.pdfHeaderHex||'').startsWith('255044462d'));return{browserVersion:await b.version(),extensionId:id,...result};}finally{if(b)await b.close().catch(()=>{});fs.rmSync(t.root,{recursive:true,force:true});}}
const s=source(),f=await serve();try{const real=await browser(f);const out={sourceBaseline:process.env.C46_SOURCE_BASELINE||'',source:s,realUnpacked:real,classification:'L4 real-unpacked production chrome.debugger/Page.printToPDF positive control plus exact-source privacy/permission/revoke findings; native permission prompt, incognito toggle, revoke/regrant and worker/browser restart remain L5 open'};out.resultSha256=crypto.createHash('sha256').update(JSON.stringify(out)).digest('hex');console.log('C46_RESULT_JSON='+JSON.stringify(out));}finally{await new Promise(r=>f.server.close(r));}
