'use strict';
const http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');
const chrome=process.env.CHROME_BIN;if(!chrome||!fs.existsSync(chrome))throw new Error('CHROME_BIN required');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(){
 const done=tx=>new Promise((res,rej)=>{tx.oncomplete=res;tx.onabort=()=>rej(tx.error||new Error('abort'));tx.onerror=()=>{};});
 const req=r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});
 const del=n=>new Promise((res,rej)=>{const r=indexedDB.deleteDatabase(n);r.onsuccess=res;r.onerror=()=>rej(r.error);r.onblocked=()=>rej(new Error('blocked delete'));});
 function open(n,v,upgrade,{closeOnVC=true,onBlocked=null}={}){return new Promise((res,rej)=>{const r=indexedDB.open(n,v);r.onupgradeneeded=e=>{try{upgrade?.(r.result,r.transaction,e);}catch(x){try{r.transaction.abort()}catch(_){}rej(x)}};r.onerror=()=>rej(r.error);r.onblocked=()=>onBlocked?.();r.onsuccess=()=>{const db=r.result;if(closeOnVC)db.onversionchange=()=>db.close();res(db)}})}
 function v3(db){db.createObjectStore('pdfs',{keyPath:'key'});db.createObjectStore('meta',{keyPath:'key'});}
 function v4(db){if(!db.objectStoreNames.contains('pdfs'))db.createObjectStore('pdfs',{keyPath:'key'});if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'});if(!db.objectStoreNames.contains('retryIndex'))db.createObjectStore('retryIndex',{keyPath:'tabId'});}
 async function seedLegacy(db){const tx=db.transaction(['pdfs','meta'],'readwrite');tx.objectStore('pdfs').add({key:'tab:5',pdfBlob:new Blob(['OLD']),createdAt:1});tx.objectStore('meta').add({key:'tab:5',createdAt:1,pdfByteLength:3});await done(tx);}
 const out=[];const name='b1-cache';await del(name).catch(()=>{});
 let db=await open(name,3,v3);await seedLegacy(db);db.close();
 db=await open(name,4,v4);out.push(['v3-v4-structural',db.version===4&&db.objectStoreNames.contains('retryIndex')]);
 let tx=db.transaction(['pdfs','meta','retryIndex'],'readonly');const old=await req(tx.objectStore('pdfs').get('tab:5'));const oldm=await req(tx.objectStore('meta').get('tab:5'));const idxCount=await req(tx.objectStore('retryIndex').count());await done(tx);out.push(['legacy-preserved-index-empty',old?.key==='tab:5'&&oldm?.key==='tab:5'&&idxCount===0]);db.close();
 let ve=false;try{await open(name,3)}catch(e){ve=e?.name==='VersionError'}out.push(['old-v3-opener-versionerror',ve]);
 // Non-owner must abort if it unexpectedly becomes upgrader.
 const n2='b1-nonowner';await del(n2).catch(()=>{});db=await open(n2,3,v3);db.close();let aborted=false;try{await open(n2,4,(_db,tx2)=>tx2.abort())}catch(e){aborted=e?.name==='AbortError'}const n2cur=await new Promise((res,rej)=>{const r=indexedDB.open(n2);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});out.push(['nonowner-abort-preserves-v3',aborted&&n2cur.version===3&&!n2cur.objectStoreNames.contains('retryIndex')]);n2cur.close();
 // Old opener that ignores versionchange blocks owner until it closes.
 const n3='b1-blocked';await del(n3).catch(()=>{});const stubborn=await open(n3,3,v3,{closeOnVC:false});let blocked=false;let ownerResolve,ownerReject;const ownerP=new Promise((res,rej)=>{ownerResolve=res;ownerReject=rej});const r=indexedDB.open(n3,4);r.onupgradeneeded=()=>v4(r.result);r.onblocked=()=>{blocked=true};r.onerror=()=>ownerReject(r.error);r.onsuccess=()=>ownerResolve(r.result);await new Promise(res=>setTimeout(res,50));stubborn.close();const owner=await ownerP;out.push(['stale-opener-blocks-until-close',blocked&&owner.version===4]);owner.close();
 // Atomic seal+pointer publish.
 const n4='b1-atomic';await del(n4).catch(()=>{});db=await open(n4,4,v4);
 tx=db.transaction(['pdfs','meta','retryIndex'],'readwrite');tx.objectStore('pdfs').add({key:'pdf:G1',pdfGeneration:'G1',blob:new Blob(['AAA'])});tx.objectStore('meta').add({key:'pdf:G1',pdfGeneration:'G1',byteLength:3,sha256:'sha256:'+ 'a'.repeat(64),sealed:true});tx.objectStore('retryIndex').put({tabId:5,pdfGeneration:'G1'});await done(tx);out.push(['atomic-seal-pointer',true]);
 // Duplicate add aborts whole tx; existing bytes/meta/pointer survive.
 let dup=false;try{tx=db.transaction(['pdfs','meta','retryIndex'],'readwrite');tx.objectStore('pdfs').add({key:'pdf:G1',pdfGeneration:'G1',blob:new Blob(['BBB'])});tx.objectStore('meta').add({key:'pdf:G1',pdfGeneration:'G1',byteLength:3,sha256:'sha256:'+ 'b'.repeat(64),sealed:true});tx.objectStore('retryIndex').put({tabId:5,pdfGeneration:'BAD'});await done(tx)}catch(e){dup=e?.name==='ConstraintError'||e?.name==='AbortError'}tx=db.transaction(['pdfs','meta','retryIndex'],'readonly');const g1=await req(tx.objectStore('pdfs').get('pdf:G1'));const gm=await req(tx.objectStore('meta').get('pdf:G1'));const pi=await req(tx.objectStore('retryIndex').get(5));await done(tx);out.push(['duplicate-create-no-overwrite',dup&&gm.sha256.endsWith('a'.repeat(64))&&pi.pdfGeneration==='G1'&&g1.pdfGeneration==='G1']);
 // Explicit abort after first add rolls all stores back.
 let rb=false;try{tx=db.transaction(['pdfs','meta','retryIndex'],'readwrite');tx.objectStore('pdfs').add({key:'pdf:G2',pdfGeneration:'G2',blob:new Blob(['CCC'])});tx.objectStore('meta').add({key:'pdf:G2',pdfGeneration:'G2',byteLength:3,sha256:'sha256:'+ 'c'.repeat(64),sealed:true});tx.objectStore('retryIndex').put({tabId:5,pdfGeneration:'G2'});tx.abort();await done(tx)}catch(_){rb=true}tx=db.transaction(['pdfs','meta','retryIndex'],'readonly');const g2=await req(tx.objectStore('pdfs').get('pdf:G2'));const g2m=await req(tx.objectStore('meta').get('pdf:G2'));const p2=await req(tx.objectStore('retryIndex').get(5));await done(tx);out.push(['abort-rolls-back-all',rb&&!g2&&!g2m&&p2.pdfGeneration==='G1']);db.close();
 // Rebootstrap owner after non-owner abort.
 const re=await open(n2,4,v4);out.push(['owner-migrates-after-nonowner-abort',re.version===4&&re.objectStoreNames.contains('retryIndex')]);re.close();
 for(const n of [name,n2,n3,n4])await del(n).catch(()=>{});return out;
}
(async()=>{const server=http.createServer((_q,r)=>{r.writeHead(200,{'content-type':'text/html'});r.end('<!doctype html><title>B1</title>')});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,debug=9334,profile=fs.mkdtempSync(path.join(os.tmpdir(),'webclip-b1-'));const proc=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu',`--user-data-dir=${profile}`,`--remote-debugging-port=${debug}`,`http://127.0.0.1:${port}/`],{stdio:['ignore','pipe','pipe']});let err='';proc.stderr.on('data',d=>err+=d);try{let pages;for(let i=0;i<80;i++){try{const r=await fetch(`http://127.0.0.1:${debug}/json/list`);if(r.ok){pages=await r.json();if(pages.length)break}}catch(_){}await sleep(100)}if(!pages?.length)throw new Error(err.slice(-2000));const p=pages.find(x=>x.type==='page')||pages[0],ws=new WebSocket(p.webSocketDebuggerUrl);await new Promise((res,rej)=>{ws.addEventListener('open',res,{once:true});ws.addEventListener('error',rej,{once:true})});let id=0;const pending=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const x=pending.get(m.id);pending.delete(m.id);m.error?x.rej(new Error(JSON.stringify(m.error))):x.res(m.result)}});const call=(method,params={})=>new Promise((res,rej)=>{const i=++id;pending.set(i,{res,rej});ws.send(JSON.stringify({id:i,method,params}))});await call('Runtime.enable');const r=await call('Runtime.evaluate',{expression:`(${fixture.toString()})()`,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));for(const [n,pass] of r.result.value)if(!pass)throw new Error(`FAIL ${n}`);console.log(`B1 PDF cache v4 Chrome IndexedDB fixture: PASS; cases=${r.result.value.length}`);for(const [n] of r.result.value)console.log(`PASS ${n}`);ws.close()}finally{proc.kill('SIGKILL');server.close();fs.rmSync(profile,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exit(1)});
