'use strict';
const http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {spawn}=require('node:child_process');
const chrome=process.env.CHROME_BIN;if(!chrome||!fs.existsSync(chrome))throw new Error('CHROME_BIN required');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function fixture(){
 const done=tx=>new Promise((res,rej)=>{tx.oncomplete=res;tx.onabort=()=>rej(tx.error||new Error('abort'));tx.onerror=()=>{};});
 const req=r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});
 const del=n=>new Promise((res,rej)=>{const r=indexedDB.deleteDatabase(n);r.onsuccess=res;r.onerror=()=>rej(r.error);r.onblocked=()=>rej(new Error('blocked delete'));});
 function open(n,v,upgrade,{closeOnVC=true}={}){return new Promise((res,rej)=>{const r=indexedDB.open(n,v);r.onupgradeneeded=e=>{try{upgrade?.(r.result,r.transaction,e);}catch(x){try{r.transaction.abort()}catch(_){}rej(x)}};r.onerror=()=>rej(r.error);r.onsuccess=()=>{const db=r.result;if(closeOnVC)db.onversionchange=()=>db.close();res(db)}})}
 function v3(db){db.createObjectStore('pdfs',{keyPath:'key'});db.createObjectStore('meta',{keyPath:'key'});}
 function v4(db){if(!db.objectStoreNames.contains('pdfs'))db.createObjectStore('pdfs',{keyPath:'key'});if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'});if(!db.objectStoreNames.contains('retryIndex'))db.createObjectStore('retryIndex',{keyPath:'tabId'});}
 const out=[],names=['b1-main','b1-nonowner','b1-blocked','b1-atomic'];for(const n of names)await del(n).catch(()=>{});
 let db=await open(names[0],3,v3);let tx=db.transaction(['pdfs','meta'],'readwrite');tx.objectStore('pdfs').add({key:'tab:5',blob:new Blob(['OLD'])});tx.objectStore('meta').add({key:'tab:5',pdfByteLength:3});await done(tx);db.close();
 db=await open(names[0],4,v4);out.push(['v3-v4-structural',db.version===4&&db.objectStoreNames.contains('retryIndex')]);tx=db.transaction(['pdfs','meta','retryIndex'],'readonly');const old=await req(tx.objectStore('pdfs').get('tab:5')),oldm=await req(tx.objectStore('meta').get('tab:5')),cnt=await req(tx.objectStore('retryIndex').count());await done(tx);out.push(['legacy-preserved-index-empty',!!old&&!!oldm&&cnt===0]);db.close();
 let ve=false;try{await open(names[0],3)}catch(e){ve=e?.name==='VersionError'}out.push(['old-v3-opener-versionerror',ve]);
 db=await open(names[1],3,v3);db.close();let ab=false;try{await open(names[1],4,(_d,t)=>t.abort())}catch(e){ab=e?.name==='AbortError'}const cur=await new Promise((res,rej)=>{const r=indexedDB.open(names[1]);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});out.push(['nonowner-abort-preserves-v3',ab&&cur.version===3&&!cur.objectStoreNames.contains('retryIndex')]);cur.close();
 const stubborn=await open(names[2],3,v3,{closeOnVC:false});let blocked=false;let rr,rj;const ownerP=new Promise((res,rej)=>{rr=res;rj=rej});const ro=indexedDB.open(names[2],4);ro.onupgradeneeded=()=>v4(ro.result);ro.onblocked=()=>blocked=true;ro.onerror=()=>rj(ro.error);ro.onsuccess=()=>rr(ro.result);await new Promise(r=>setTimeout(r,80));stubborn.close();const owner=await ownerP;out.push(['stale-opener-blocks-until-close',blocked&&owner.version===4]);owner.close();
 db=await open(names[3],4,v4);tx=db.transaction(['pdfs','meta','retryIndex'],'readwrite');tx.objectStore('pdfs').add({key:'pdf:G1',pdfGeneration:'G1',blob:new Blob(['AAA'])});tx.objectStore('meta').add({key:'pdf:G1',pdfGeneration:'G1',byteLength:3,sha256:'sha256:'+ 'a'.repeat(64),sealed:true});tx.objectStore('retryIndex').put({tabId:5,pdfGeneration:'G1'});await done(tx);out.push(['atomic-seal-pointer',true]);
 let dup=false;try{tx=db.transaction(['pdfs','meta','retryIndex'],'readwrite');tx.objectStore('pdfs').add({key:'pdf:G1',pdfGeneration:'G1',blob:new Blob(['BBB'])});tx.objectStore('meta').add({key:'pdf:G1',pdfGeneration:'G1',byteLength:3,sha256:'sha256:'+ 'b'.repeat(64),sealed:true});tx.objectStore('retryIndex').put({tabId:5,pdfGeneration:'BAD'});await done(tx)}catch(e){dup=e?.name==='ConstraintError'||e?.name==='AbortError'}tx=db.transaction(['meta','retryIndex'],'readonly');const gm=await req(tx.objectStore('meta').get('pdf:G1')),pi=await req(tx.objectStore('retryIndex').get(5));await done(tx);out.push(['duplicate-create-no-overwrite',dup&&gm.sha256.endsWith('a'.repeat(64))&&pi.pdfGeneration==='G1']);
 let rb=false;try{tx=db.transaction(['pdfs','meta','retryIndex'],'readwrite');tx.objectStore('pdfs').add({key:'pdf:G2',pdfGeneration:'G2',blob:new Blob(['CCC'])});tx.objectStore('meta').add({key:'pdf:G2',pdfGeneration:'G2',byteLength:3,sha256:'sha256:'+ 'c'.repeat(64),sealed:true});tx.objectStore('retryIndex').put({tabId:5,pdfGeneration:'G2'});tx.abort();await done(tx)}catch(_){rb=true}tx=db.transaction(['pdfs','meta','retryIndex'],'readonly');const g2=await req(tx.objectStore('pdfs').get('pdf:G2')),g2m=await req(tx.objectStore('meta').get('pdf:G2')),p2=await req(tx.objectStore('retryIndex').get(5));await done(tx);out.push(['abort-rolls-back-all',rb&&!g2&&!g2m&&p2.pdfGeneration==='G1']);db.close();
 const re=await open(names[1],4,v4);out.push(['owner-migrates-after-nonowner-abort',re.version===4&&re.objectStoreNames.contains('retryIndex')]);re.close();
 for(const n of names)await del(n).catch(()=>{});return out;
}
(async()=>{const server=http.createServer((_q,r)=>{r.writeHead(200,{'content-type':'text/html'});r.end('<!doctype html><title>B1 fixture</title>')});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,target=`http://127.0.0.1:${port}/`,debug=9334,profile=fs.mkdtempSync(path.join(os.tmpdir(),'webclip-b1-'));const proc=spawn(chrome,['--headless=new','--no-sandbox','--disable-gpu',`--user-data-dir=${profile}`,`--remote-debugging-port=${debug}`,target],{stdio:['ignore','pipe','pipe']});let err='';proc.stderr.on('data',d=>err+=d);try{let page;for(let i=0;i<100;i++){try{const r=await fetch(`http://127.0.0.1:${debug}/json/list`);if(r.ok){const pages=await r.json();page=pages.find(x=>x.type==='page'&&String(x.url||'').startsWith(target));if(page)break}}catch(_){}await sleep(100)}if(!page)throw new Error(`fixture target unavailable: ${err.slice(-1500)}`);const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise((res,rej)=>{ws.addEventListener('open',res,{once:true});ws.addEventListener('error',rej,{once:true})});let id=0;const pending=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const x=pending.get(m.id);pending.delete(m.id);m.error?x.rej(new Error(JSON.stringify(m.error))):x.res(m.result)}});const call=(method,params={})=>new Promise((res,rej)=>{const i=++id;pending.set(i,{res,rej});ws.send(JSON.stringify({id:i,method,params}))});await call('Runtime.enable');const origin=await call('Runtime.evaluate',{expression:'location.href',returnByValue:true});if(!String(origin.result.value||'').startsWith(target))throw new Error(`wrong CDP origin: ${origin.result.value}`);const r=await call('Runtime.evaluate',{expression:`(${fixture.toString()})()`,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));for(const [n,pass] of r.result.value)if(!pass)throw new Error(`FAIL ${n}`);console.log(`B1 PDF cache v4 Chrome IndexedDB fixture: PASS; cases=${r.result.value.length}`);for(const [n] of r.result.value)console.log(`PASS ${n}`);ws.close()}finally{proc.kill('SIGKILL');server.close();fs.rmSync(profile,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exit(1)});
