const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const content = fs.readFileSync('content.js', 'utf8');
const frame = fs.readFileSync('frame-agent.js', 'utf8');
assert(content.includes('function collectTagCandidatesBounded(ownerDoc, tag, limit = 5000)'));
assert(!content.includes("[...ownerDoc.querySelectorAll(tag)].slice(0, 5000)"));
assert(content.includes('collectFrameElementsBounded(ownerDoc, 256)'));
assert(!content.includes("[...ownerDoc.querySelectorAll('iframe, frame')].slice(0, 256)"));
assert(frame.includes('function tagCandidatesBounded(tag,limit=5000)'));
assert(!frame.includes("[...document.querySelectorAll(String(l.tag||'*').toLowerCase()||'*')].slice(0,5000)"));
const match = content.match(/  function collectTagCandidatesBounded\(ownerDoc, tag, limit = 5000\) \{[\s\S]*?\n  \}\n\n  function collectFrameElementsBounded/);
assert(match, 'bounded helper extraction');
const fnSource = match[0].replace(/\n\n  function collectFrameElementsBounded[\s\S]*$/, '');
let reads = 0;
const collection = new Proxy({ length: 100000 }, { get(target, prop) { if (/^\d+$/.test(String(prop))) { reads += 1; return { nodeType: 1, index: Number(prop) }; } return target[prop]; } });
const sandbox = { ownerDoc: { getElementsByTagName() { return collection; } }, result: null };
vm.createContext(sandbox);
vm.runInContext(`${fnSource}\nresult = collectTagCandidatesBounded(ownerDoc, 'div', 5000);`, sandbox);
assert.strictEqual(sandbox.result.length, 5000);
assert.strictEqual(reads, 5000, 'must not enumerate beyond the declared limit');
console.log('P1-155 bounded DOM candidate enumeration regression PASS');
