'use strict';
const fs=require('node:fs');
const assert=require('node:assert/strict');
const sw=fs.readFileSync('service-worker.js','utf8');
const off=fs.readFileSync('offscreen.js','utf8');
let facts=0; function has(src,re,msg){assert.match(src,re,msg);facts++;} function lacks(src,re,msg){assert.doesNotMatch(src,re,msg);facts++;}
has(sw,/const PDF_CACHE_DB_VERSION = 3;/,'worker cache still v3');
has(off,/const PDF_CACHE_DB_VERSION = 3;/,'offscreen cache still v3');
has(sw,/function pdfCacheKey\(tabId\)[\s\S]*?`tab:\$\{tabId\}`/,'tab alias remains identity');
has(sw,/objectStore\(PDF_CACHE_STORE\)\.put\(normalizedRecord\)/,'payload writer is replace-capable');
has(sw,/objectStore\(PDF_CACHE_META_STORE\)\.put\(metadata\)/,'metadata writer is replace-capable');
has(sw,/async function getValidCachedPdfForTab\(tabId\)/,'retry begins from tab');
has(sw,/pdfCacheKey: String\(cached\.key \|\| pdfCacheKey\(tabId\)\)/,'offscreen upload can receive tab fallback');
has(off,/getPdfCacheRecord\(String\(spec\.pdfCacheKey \|\| ''\)/,'offscreen re-reads key at transfer time');
has(off,/getPdfCacheRecord\(String\(message\.pdfCacheKey \|\| ''\)/,'blob URL also re-reads generic key');
has(off,/openDbBounded\(PDF_CACHE_DB_NAME, PDF_CACHE_DB_VERSION,[\s\S]*?createObjectStore\(PDF_CACHE_STORE/,'offscreen is current structural owner');
has(off,/createObjectStore\(PDF_CACHE_META_STORE/,'offscreen creates meta store');
lacks(sw,/PDF_CACHE_RETRY_INDEX_STORE/,'no v4 retryIndex constant');
lacks(sw,/pdfGeneration/,'no production pdfGeneration authority');
lacks(off,/expectedSha256/,'offscreen does not verify expected SHA-256');
lacks(off,/expectedPdfBytes/,'offscreen does not require expected exact bytes in pdf-cache upload contract');
lacks(sw,/sha256[^\n]*PDF|pdfSha256|PDF_SHA256/,'sealed PDF digest absent in current cache contract');
lacks(sw,/\.add\(normalizedRecord\)/,'worker exact generation create-once add absent');
lacks(sw,/WEBCLIP_PDF_CACHE_SCHEMA_READY/,'no worker cache schema-ready handshake');
lacks(off,/WEBCLIP_OFFSCREEN_PROTOCOL_INFO/,'current offscreen has no U0 protocol-info contract');
has(sw,/const temporaryCacheKey = `local-download:\$\{operationId\}`/,'local download uses caller-correlated temporary alias');
has(sw,/deleteCachedPdfByKey\(temporaryCacheKey\)/,'local temporary cache deleted by generic key');
has(sw,/deleteCachedPdfByKey|deleteCachedPdf/,'generic delete APIs still exist');
lacks(sw,/legacy-unbound/,'legacy v3 classification absent');
lacks(off,/schemaRole/,'offscreen schema ownership role absent');
lacks(sw,/compare.*retryIndex|retryIndex.*compare/,'pointer CAS absent');
console.log(`B1 PDF cache v4 current-source inventory: PASS; RED facts=${facts}`);
