'use strict';
// P1-164 live Yandex observer. GET-only; never owns revoke/move admission.
const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'),API='https://cloud-api.yandex.net/v1/disk';
const INPUT_SCHEMA='webclip-p1-164-live-observer-input/v2',OUTPUT_SCHEMA='webclip-p1-164-live-observation/v2',KIND='publication-revoke-trash';
const PHASES=new Set(['prepared','revoke-admitted-unknown','revoke-verified','move-admitted-unknown','remote-verified','manual-resolution']);
const SOURCES=new Set(['prepared','revoke-admitted-unknown','revoke-verified','move-admitted-unknown','remote-verified']);
function fail(code,msg=code){const e=new Error(msg);e.code=code;throw e}
function norm(v){let s=String(v||'').trim().replace(/\\/g,'/').replace(/^disk:/i,'');if(!s)return'';if(!s.startsWith('/'))s='/'+s;const a=[];for(const x of s.split('/')){if(!x||x==='.')continue;if(x==='..'){a.pop();continue}a.push(x)}return'/'+a.join('/')}
function inside(v,r){v=norm(v);r=norm(r);return!!(v&&r&&r!=='/'&&(v===r||v.startsWith(r+'/')))}
function req(v,n){v=String(v||'').trim();if(!v)fail('CONFIG_IDENTITY_MISSING',n);if(v.length>8192)fail('CONFIG_IDENTITY_TOO_LARGE',n);return v}
function keys(o,a,c){for(const k of Object.keys(o||{}))if(!a.includes(k))fail(c,k)}
function validateConfig(x){
 if(!x||typeof x!=='object'||Array.isArray(x))fail('CONFIG_OBJECT_REQUIRED');keys(x,['schema','testedSourceSha','kind','phase','manualResolutionSourcePhase','receiptAnchor','receipt','currentContext','watchSeconds'],'CONFIG_FIELD_UNEXPECTED');
 if(x.schema!==INPUT_SCHEMA)fail('CONFIG_SCHEMA_INVALID');if(!/^[0-9a-f]{40}$/.test(x.testedSourceSha||''))fail('CONFIG_TESTED_SOURCE_SHA_INVALID');if(x.kind!==KIND)fail('CONFIG_KIND_INVALID');if(!PHASES.has(x.phase))fail('CONFIG_PHASE_INVALID');
 const ep=x.phase==='manual-resolution'?String(x.manualResolutionSourcePhase||''):x.phase;if(!SOURCES.has(ep))fail('CONFIG_SOURCE_PHASE_INVALID');
 const a=x.receiptAnchor;if(!a||typeof a!=='object'||Array.isArray(a))fail('CONFIG_RECEIPT_ANCHOR_REQUIRED');keys(a,['receiptId','receiptUpdatedAt','exportedAt'],'CONFIG_RECEIPT_ANCHOR_FIELD_UNEXPECTED');
 const receiptId=req(a.receiptId,'receiptId');if(!/^destructive:publication-revoke-trash:[A-Za-z0-9._:-]{1,128}$/.test(receiptId))fail('CONFIG_RECEIPT_ID_INVALID');
 const receiptUpdatedAt=Number(a.receiptUpdatedAt);if(!Number.isSafeInteger(receiptUpdatedAt)||receiptUpdatedAt<=0)fail('CONFIG_RECEIPT_UPDATED_AT_INVALID');
 const exportedAtMs=Date.parse(String(a.exportedAt||''));if(!Number.isFinite(exportedAtMs)||exportedAtMs<=0)fail('CONFIG_RECEIPT_EXPORTED_AT_INVALID');
 const anchor=Object.freeze({receiptId,receiptUpdatedAt,exportedAt:new Date(exportedAtMs).toISOString()});
 const r=x.receipt;if(!r||typeof r!=='object'||Array.isArray(r))fail('CONFIG_RECEIPT_REQUIRED');keys(r,['operationId','accountUid','rootPath','sourcePath','targetPath','sourceResourceId','sourcePublicUrl'],'CONFIG_RECEIPT_FIELD_UNEXPECTED');
 const receipt={operationId:req(r.operationId,'operationId'),accountUid:req(r.accountUid,'accountUid'),rootPath:norm(req(r.rootPath,'rootPath')),sourcePath:norm(req(r.sourcePath,'sourcePath')),targetPath:norm(req(r.targetPath,'targetPath')),sourceResourceId:req(r.sourceResourceId,'resourceId'),sourcePublicUrl:req(r.sourcePublicUrl,'publicUrl')};
 if(receipt.rootPath==='/'||!inside(receipt.sourcePath,receipt.rootPath)||!inside(receipt.targetPath,receipt.rootPath))fail('CONFIG_PATH_SCOPE_INVALID');
 const c=x.currentContext;if(!c||typeof c!=='object'||Array.isArray(c))fail('CONFIG_CURRENT_CONTEXT_REQUIRED');keys(c,['rootPath'],'CONFIG_CURRENT_CONTEXT_FIELD_UNEXPECTED');const currentRootPath=norm(req(c.rootPath,'currentRootPath'));
 const watch=x.watchSeconds===undefined?0:Number(x.watchSeconds);if(!Number.isInteger(watch)||watch<0||watch>120)fail('CONFIG_WATCH_SECONDS_INVALID');
 return Object.freeze({testedSourceSha:x.testedSourceSha,kind:KIND,phase:x.phase,manualResolutionSourcePhase:x.phase==='manual-resolution'?ep:'',effectivePhase:ep,watchSeconds:watch,receiptAnchor:anchor,receipt:Object.freeze(receipt),currentContext:Object.freeze({rootPath:currentRootPath})})
}
function res(state='present',p={}){return Object.freeze({state,type:'file',pathMatches:true,resourceIdMatches:true,isPublic:false,publicUrlMatches:true,...p})}
function exact(o){return o?.state==='present'&&o.type==='file'&&o.pathMatches===true&&o.resourceIdMatches===true}
function conflict(o){return o?.state==='present'&&(!o.pathMatches||!o.resourceIdMatches||o.type!=='file')}
function v(state,next,terminal=true){return Object.freeze({state,safeNextAction:next,terminal})}
function classifyObservation(i={}){
 const s=i.source||res('error'),t=i.target||res('error'),p=String(i.phase||''),a=String(i.accountState||'present');
 if(a==='auth-rejected'||[s.state,t.state].includes('auth-rejected'))return v('auth-rejected','reauthorize-then-observe-only');
 if(a==='rate-limited'||[s.state,t.state].includes('rate-limited'))return v('rate-limited','delay-then-observe-only',false);
 if(a!=='present'||[s.state,t.state].includes('error'))return v('observation-error','retry-read-only-observation',false);
 if(i.accountMatches!==true)return v('account-conflict','stop-no-retry');if(i.rootMatches!==true)return v('root-conflict','stop-no-retry');
 if(p==='prepared'){
  if(conflict(s))return v('source-replaced','stop-no-retry');if(!exact(s))return v('source-missing','stop-no-retry');if(s.isPublic&&!s.publicUrlMatches)return v('public-url-conflict','stop-no-retry');if(!s.isPublic)return v('already-private','use-normal-private-trash-path');if(!i.samePath&&t.state==='present')return v('target-occupied','stop-no-retarget');return v('pre-admission-ready','return-to-webclip-for-admission')
 }
 if(p==='revoke-admitted-unknown'){
  if(conflict(s))return v('source-replaced','manual-resolution-no-retry');if(!exact(s))return v('revoke-settlement-unknown','observe-only-never-repeat-unpublish',false);if(!s.isPublic)return v('revoke-settled-private',i.samePath?'local-finalize-only':'continue-from-revoke-verified');if(!s.publicUrlMatches)return v('public-url-conflict','manual-resolution-no-retry');return v('revoke-not-observed','observe-only-never-repeat-unpublish',false)
 }
 if(p==='revoke-verified'){
  if(conflict(s)||!exact(s)||s.isPublic)return v('source-conflict','manual-resolution-no-retry');if(i.samePath)return v('remote-terminal-private','local-finalize-only');if(t.state==='missing')return v('pre-move-ready','return-to-webclip-for-single-move-admission');return v('target-occupied','manual-resolution-no-retarget')
 }
 if(p==='move-admitted-unknown'){
  if(i.samePath)return v('phase-conflict','manual-resolution-no-retry');if(conflict(t))return v('target-replaced','manual-resolution-no-retry');if(exact(t)){if(t.isPublic)return v('target-public','manual-resolution-no-retry');if(exact(s))return v('dual-location','observe-only-never-repeat-move',false);return v('move-settled-private','local-finalize-only')};if(conflict(s))return v('source-replaced','manual-resolution-no-retry');if(exact(s)&&s.isPublic)return v('source-public','manual-resolution-no-retry');if(exact(s))return v('move-not-observed','observe-only-never-repeat-move',false);return v('move-settlement-unknown','observe-only-never-repeat-move',false)
 }
 if(p==='remote-verified'){const z=i.samePath?s:t;if(conflict(z))return v('terminal-replaced','manual-resolution-local-only');if(!exact(z))return v('terminal-not-visible','manual-resolution-local-only',false);if(z.isPublic)return v('terminal-public','manual-resolution-local-only');return v('terminal-confirmed','local-finalize-only')}
 return v('phase-invalid','stop-no-retry')
}
function digests(c){const r=c.receipt,h=(k,x)=>'sha256:'+crypto.createHash('sha256').update(`WEBCLIP_P1_164_OBSERVER\0${k}\0${x}`).digest('hex');return Object.freeze({operationId:h('op',r.operationId),accountUid:h('account',r.accountUid),rootPath:h('root',r.rootPath),sourcePath:h('source',r.sourcePath),targetPath:h('target',r.targetPath),resourceId:h('resource',r.sourceResourceId),publicUrl:h('public',r.sourcePublicUrl),currentRootPath:h('current-root',c.currentContext.rootPath)})}
function receiptAnchor(c){const a=c.receiptAnchor,h=x=>'sha256:'+crypto.createHash('sha256').update(`WEBCLIP_P1_164_OBSERVER\0receipt-id\0${x}`).digest('hex');return Object.freeze({receiptIdDigest:h(a.receiptId),receiptUpdatedAt:a.receiptUpdatedAt,exportedAt:a.exportedAt})}
function safe(o){return o&&Object.freeze({state:o.state,type:o.type||'',pathMatches:o.pathMatches===true,resourceIdMatches:o.resourceIdMatches===true,isPublic:o.isPublic===true,publicUrlMatches:o.publicUrlMatches===true,httpStatus:Number(o.httpStatus)||0,errorClass:String(o.errorClass||'')})}
function outside(p){p=String(p||'').trim();if(!p)fail('PRIVATE_PATH_REQUIRED');const a=path.resolve(p),r=path.relative(ROOT,a);if(!r.startsWith('..')&&!path.isAbsolute(r))fail('PRIVATE_PATH_INSIDE_REPOSITORY');return a}
function liveEnv(e=process.env){if(e.CI&&String(e.CI).toLowerCase()!=='false')fail('LIVE_OBSERVER_REFUSES_CI');const t=String(e.WEBCLIP_YANDEX_OAUTH_TOKEN||'').trim();if(!t)fail('LIVE_OBSERVER_TOKEN_REQUIRED');if(t.length>16384)fail('LIVE_OBSERVER_TOKEN_TOO_LARGE');return t}
function exactHead(sha){if(execFileSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim()!==sha)fail('TESTED_SOURCE_SHA_MISMATCH');if(execFileSync('git',['status','--porcelain','--untracked-files=no'],{cwd:ROOT,encoding:'utf8'}).trim())fail('TRACKED_WORKTREE_DIRTY')}
function releaseIdentity(){const f=path.join(ROOT,'project_tools','test_p1_231_s0e_identity_engine_source_spec_model.js'),l=execFileSync(process.execPath,[f],{cwd:ROOT,encoding:'utf8'}).trim().split(/\r?\n/).reverse().find(x=>x.startsWith('P1-231 S0-E identity engine source-spec model: PASS'));if(!l)fail('RELEASE_IDENTITY_UNAVAILABLE');const q={};for(const z of l.split(';').slice(1)){const n=z.indexOf('=');if(n>0)q[z.slice(0,n).trim()]=z.slice(n+1).trim()}if(!/^sha256:[0-9a-f]{64}$/.test(q.rpf||'')||!/^sha256:[0-9a-f]{64}$/.test(q.yandex_qcf||''))fail('RELEASE_IDENTITY_INVALID');return{rpf:q.rpf,yandexQcf:q.yandex_qcf}}
async function get(token,endpoint='',query={}){const u=new URL(API+endpoint);for(const[k,x]of Object.entries(query))if(x!=='')u.searchParams.set(k,String(x));const c=new AbortController(),tm=setTimeout(()=>c.abort(),10000);let r;try{r=await fetch(u,{method:'GET',headers:{Authorization:`OAuth ${token}`,Accept:'application/json'},redirect:'error',signal:c.signal})}catch(e){return{ok:false,status:0,errorClass:c.signal.aborted||e?.name==='AbortError'?'timeout':'network'}}finally{clearTimeout(tm)}let d=null;try{d=await r.json()}catch(_){}if(r.ok)return{ok:true,status:r.status,data:d};if(r.status===404)return{ok:false,status:404,errorClass:'missing'};if(r.status===401||r.status===403)return{ok:false,status:r.status,errorClass:'auth-rejected'};if(r.status===429)return{ok:false,status:429,errorClass:'rate-limited'};return{ok:false,status:r.status,errorClass:r.status>=500?'provider-5xx':'http-error'}}
async function account(token,uid){const r=await get(token);if(!r.ok)return{state:r.errorClass,matches:false,httpStatus:r.status};const x=String(r.data?.user?.uid||'').trim();return x?{state:'present',matches:x===uid,httpStatus:r.status}:{state:'error',matches:false,errorClass:'uid-missing'}}
async function resource(token,p,id,publicUrl=''){const r=await get(token,'/resources',{path:p,fields:'type,path,resource_id,public_url'});if(!r.ok)return r.errorClass==='missing'?res('missing',{type:'',pathMatches:false,resourceIdMatches:false,publicUrlMatches:false}):res(['auth-rejected','rate-limited'].includes(r.errorClass)?r.errorClass:'error',{httpStatus:r.status,errorClass:r.errorClass});const d=r.data||{},url=String(d.public_url||'');return res('present',{type:String(d.type||''),pathMatches:norm(d.path||p)===p,resourceIdMatches:String(d.resource_id||'')===id,isPublic:!!url,publicUrlMatches:!publicUrl||url===publicUrl,httpStatus:r.status})}
async function once(token,c){const a=await account(token,c.receipt.accountUid),samePath=c.receipt.sourcePath===c.receipt.targetPath,s=await resource(token,c.receipt.sourcePath,c.receipt.sourceResourceId,c.receipt.sourcePublicUrl),t=samePath?s:await resource(token,c.receipt.targetPath,c.receipt.sourceResourceId);const i={phase:c.effectivePhase,accountState:a.state,accountMatches:a.matches===true,rootMatches:c.currentContext.rootPath===c.receipt.rootPath,samePath,source:s,target:t};return{account:a,...i,classification:classifyObservation(i)}}
async function observe(token,c){const start=Date.now(),end=start+c.watchSeconds*1000,attempts=[];let o;do{o=await once(token,c);attempts.push({attempt:attempts.length+1,elapsedMs:Date.now()-start,state:o.classification.state});if(o.classification.terminal||!c.watchSeconds||Date.now()>=end)break;await new Promise(r=>setTimeout(r,Math.min(5000,750+attempts.length*250,end-Date.now())))}while(Date.now()<end);let cl=o.classification;if(c.watchSeconds&&!cl.terminal&&Date.now()>=end)cl=v('observation-window-expired',cl.safeNextAction);return{...o,classification:cl,attempts,elapsedMs:Date.now()-start}}
function output(c,id,o){return Object.freeze({schema:OUTPUT_SCHEMA,generatedAt:new Date().toISOString(),evidenceClass:'live-provider-observation-only',testedSourceSha:c.testedSourceSha,subject:id,kind:KIND,phase:c.phase,manualResolutionSourcePhase:c.manualResolutionSourcePhase,effectivePhase:c.effectivePhase,receiptAnchor:receiptAnchor(c),identityDigests:digests(c),context:{accountState:o.account.state,accountMatches:o.accountMatches,rootMatches:o.rootMatches,sameSourceTargetPath:o.samePath},source:safe(o.source),target:safe(o.target),classification:o.classification,watch:{requestedSeconds:c.watchSeconds,elapsedMs:o.elapsedMs,attempts:o.attempts},limitations:['observer-issued-no-provider-mutation','private-receipt-anchor-is-snapshot-not-command-admission-proof','does-not-authenticate-private-export-origin','does-not-prove-webclip-command-admission-by-itself','does-not-prove-running-extension-source-sha','does-not-close-p1-164-by-itself','does-not-advance-yandex-qcf-by-itself']})}
async function main(){const a=process.argv.slice(2),live=a.includes('--live'),i=a.indexOf('--config');if(a.includes('--help'))return process.stdout.write('WEBCLIP_YANDEX_OAUTH_TOKEN=... node project_tools/yandex_p1_164_live_observer.js --live --config /absolute/private/input.json\n');if(!live||i<0)fail('LIVE_ACK_REQUIRED');const p=outside(a[i+1]);let text;try{const s=fs.statSync(p);if(!s.isFile()||s.size>65536)fail('CONFIG_FILE_INVALID');text=fs.readFileSync(p,'utf8')}catch(e){if(e?.code==='CONFIG_FILE_INVALID')throw e;fail('CONFIG_FILE_UNREADABLE')}let raw;try{raw=JSON.parse(text)}catch(_){fail('CONFIG_JSON_INVALID')}const c=validateConfig(raw);exactHead(c.testedSourceSha);const token=liveEnv();process.stdout.write(JSON.stringify(output(c,releaseIdentity(),await observe(token,c)),null,2)+'\n')}
if(require.main===module)main().catch(e=>{process.stderr.write(`${String(e?.code||'LIVE_OBSERVER_FAILED')}: ${String(e?.message||'failed').slice(0,200)}\n`);process.exitCode=1});
module.exports=Object.freeze({INPUT_SCHEMA,OUTPUT_SCHEMA,KIND,norm,inside,validateConfig,res,classifyObservation,digests,receiptAnchor,safe,outside,liveEnv,output});
